### ISSUE TITLE
👋

### ISSUE THREAD

**Issue by Patrick-Erichsen** [dgroomes/swing-playground#1]
Hey David, long time no see! I googled "swing ui playground" today and found myself here from the top search result 😅 I got a good laugh out of the Overview section ("It's 2023 and we're learning Swing?") 

I'm building with Swing for some work on the JetBrains extension for Continue that I'm working on, e.g. https://github.com/continuedev/continue/blob/main/extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/ToolTipComponent.kt

**Comment by dgroomes** [comment]
Hey Patrick, that's so funny I didn't mean to SEO squat a top search result but it's really funny you found this repo and reached out!

That's super neat, I'll have to check out Continue and the JetBrains/VSCode plugins. I was actually hacking on a fork of another LLM-powered plugin I think at the time I made this Swing repo, just so I could get some working knowledge/reference of Swing and Intellij plugin code. But I haven't used it for many months, and I'm eager to get lots of leverage out of these types of tools.

Stuff like <https://github.com/continuedev/continue/blob/056a68d06186b567510f379fd27990896b46f15c/docs/docs/customize/deep-dives/codebase.md> 👀  looks really really neat and I don't know how Continue was not on my radar!

**Comment by Patrick-Erichsen** [comment]
Small world of Swing UI devs in 2024 I suppose haha, perhaps not the most pleasant DX but still nice that you get so much control in IntelliJ over the in-editor UI. 

> eager to get lots of leverage out of these types of tools.

But yes agreed, fun space to build in!

If your curious, this is the more developer/internal facing deep dive on how we do codebase indexing: https://github.com/continuedev/continue/blob/main/core/indexing/README.md
